---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: ankushpatil488
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Stop and remove existing container frontend_container if present and running
      shell: docker stop frontend_container && docker rm frontend_container
      ignore_errors: true
    - name: Stop and remove existing container backend_container if present and running
      shell: docker stop backend_container && docker rm backend_container
      ignore_errors: true
    - name: Stop and remove existing container  flask_container if present and running
      shell: docker stop flask_container && docker rm flask_container
      ignore_errors: true
    - name: Stop and remove existing container bookreview_db_container if present and running
      shell: docker stop bookreview_db_container && docker rm bookreview_db_container
      ignore_errors: true
      
    - name: Stop and remove existing container logstash if present and running
      shell: docker stop logstash && docker rm logstash
      ignore_errors: true

    - name: Stop and remove existing container kibana if present and running
      shell: docker stop kibana && docker rm kibana
      ignore_errors: true

    - name: Stop and remove existing container  elasticsearchif present and running
      shell: docker stop elasticsearch && docker rm elasticsearch
      ignore_errors: true


    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: ./

    - name: Run docker compose up command
      docker_compose:
        project_src: ./
        state: present
        pull: yes


