---
- name: Deploy application to EC2
  hosts: ec2
  remote_user: ubuntu
  become: yes
  vars:
    project_dir: /home/ubuntu/spe-project
    ansible_python_interpreter: /usr/bin/python3  # Ensure Ansible uses the correct Python interpreter
  tasks:
    - name: Gathering Facts
      setup:

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Stop and remove existing containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - frontend_container
        - backend_container
        - flask_container
        - bookreview_db_container

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: "{{ project_dir }}/docker-compose.yml"

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ project_dir }}"

    # Add additional tasks if required, such as setting up networks or volumes

