version: '3'

services:
  userservice:
    image: ankushpatil0125/backend_image
    container_name: backend_container
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://bookreview_db_container/bookReviewDB?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - book-review-network 
    depends_on:
      - bookreview_db
    volumes:
      - /home:/logs
      
  bookreview_db:
    image: mysql:8
    container_name: bookreview_db_container
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookReviewDB
    volumes:
      - bookreview_db:/var/lib/mysql
    networks:
      - book-review-network 
      
  flaskBackend:
    image: ankushpatil0125/flask_image
    container_name : flask_container
    #build:
      #context: .
      #dockerfile: ./Dockerfile
    ports:
      - 5002:5002
    networks:
      - book-review-network
      
  bookreviewfrontend:
    image: ankushpatil0125/frontend_image
    container_name: frontend_container
    #build:
      #context: .
      #dockerfile: ./Dockerfile
    #environment:
      #NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - book-review-network 
      
networks:
  book-review-network:
    driver: bridge

volumes:
  bookreview_db:

