version: '3'

services:
  userservice:
    image: backend_image:v1
    container_name: backend_container
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://bookreview_db/bookReviewDB?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - bank-network
    depends_on:
      - bookreview_db
    volumes:
      - /home:/logs
      
  bookreview_db:
    image: mysql:8
    container_name: bookreview_db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookReviewDB
    volumes:
      - bookreview_db:/var/lib/mysql
    networks:
      - bank-network
      
  flaskBackend:
    image: flask_image:v2
    container_name : flask_containerv1
    #build:
      #context: .
      #dockerfile: ./Dockerfile
    ports:
      - 5002:5002
    networks:
      - bank-network
      
  bookreviewfrontend:
    image: frontend_image:v6
    container_name: frontend_containerv7
    #build:
      #context: .
      #dockerfile: ./Dockerfile
    #environment:
      #NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - bank-network  
      
networks:
  bank-network:
    driver: bridge

volumes:
  bookreview_db:

