http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
xpack.monitoring.enabled: false
#xpack.monitoring.elasticsearch.hosts: ["localhost:9200"]

xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
